// Code generated by sqlc. DO NOT EDIT.

package order

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgtype"
)

// Orders
type Order struct {
	// Unique order id
	ID         pgtype.UUID
	CreateTime time.Time
	// Order request data
	OrderRequest json.RawMessage
	// Reference Retrieval Number
	Rrn string
	// Order id
	OrderID string
	// Seller if (owner credentials)
	SellerID string
}
