// Code generated by sqlc. DO NOT EDIT.

package order

import (
	"context"
)

type Querier interface {
	AddOrder(ctx context.Context, arg AddOrderParams) (Order, error)
	DeleteOrder(ctx context.Context, arg DeleteOrderParams) (Order, error)
	GetOrder(ctx context.Context, arg GetOrderParams) (GetOrderRow, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
